import type { Metadata } from "next";
import "../styles/variables.scss";

export const metadata: Metadata = {
  title: "Portfolio26",
  description: "Generated by jinyoo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body>{children}</body>
    </html>
  );
}
