import type { Metadata } from "next";

import Footer from "@/components/Footer";

import "../styles/global.scss";

export const metadata: Metadata = {
  title: "Portfolio26",
  description: "Generated by jinyoo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <head>
        <link
          rel="stylesheet"
          href="https://use.typekit.net/hkg4vmv.css"
        ></link>
      </head>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
