import type { Metadata } from "next";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ScrambleText from "@/components/ScrambleText";
import ScrollSmootherProvider from "@/components/ScrollSmoother";

import "../styles/global.scss";

export const metadata: Metadata = {
  title: "Portfolio26",
  description: "Generated by jinyoo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <link
          rel="stylesheet"
          href="https://use.typekit.net/hkg4vmv.css"
        ></link>
      </head>
      <body>
        <ScrollSmootherProvider>
          <Header />
          <ScrambleText />
          {children}
          <Footer />
        </ScrollSmootherProvider>
      </body>
    </html>
  );
}
